# #DEV
FROM node:16-alpine
# RUN apk add --no-cache tzdata
# ENV TZ America/La_Paz
WORKDIR /usr/app
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run codegen
EXPOSE 4000

CMD ["npm", "run", "dev"]