# #DEV
FROM node:16-alpine
# RUN apk add --no-cache tzdata
# ENV TZ America/La_Paz
WORKDIR /usr/app
RUN npm install -g pnpm@8.15.4
COPY package.json pnpm-lock.yaml .npmrc ./
RUN pnpm install --frozen-lockfile
COPY . .

RUN pnpm codegen
EXPOSE 4000

CMD ["pnpm", "dev"]
